stations:
    atm: ["Saybrook", "BucksPond"]
    h2o: {"Saybrook" : ["Saybrook", 2],
          "Wildcat"  : ["Saybrook", 2],
          "BigDitch" : ["Saybrook", 2],
	 } 

directories:
    in_dir: "."
    out_dir: "."
    atm_df:  "."
